services:
  # Apache Kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000 #2 sec
    networks:
      - ms-network

networks:
  ms-network:
    name: ms-network
    driver: bridge